// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/members": {
    params: {};
  };
  "/members/:id": {
    params: {
      "id": string;
    };
  };
  "/staff": {
    params: {};
  };
  "/plans": {
    params: {};
  };
  "/payments": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/logout" | "/signup" | "/login" | "/verify" | "/onboarding" | "/members" | "/members/:id" | "/staff" | "/plans" | "/payments" | "/*";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/signup" | "/login" | "/verify" | "/onboarding";
  };
  "routes/_auth.signup.tsx": {
    id: "routes/_auth.signup";
    page: "/signup";
  };
  "routes/_auth.login.tsx": {
    id: "routes/_auth.login";
    page: "/login";
  };
  "routes/_auth.verify.tsx": {
    id: "routes/_auth.verify";
    page: "/verify";
  };
  "routes/_auth.onboarding.tsx": {
    id: "routes/_auth.onboarding";
    page: "/onboarding";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/members" | "/members/:id" | "/staff" | "/plans" | "/payments";
  };
  "routes/_app._index.tsx": {
    id: "routes/_app._index";
    page: "/";
  };
  "routes/_app.members.tsx": {
    id: "routes/_app.members";
    page: "/members";
  };
  "routes/_app.members.$id.tsx": {
    id: "routes/_app.members.$id";
    page: "/members/:id";
  };
  "routes/_app.staff.tsx": {
    id: "routes/_app.staff";
    page: "/staff";
  };
  "routes/_app.plans.tsx": {
    id: "routes/_app.plans";
    page: "/plans";
  };
  "routes/_app.payments.tsx": {
    id: "routes/_app.payments";
    page: "/payments";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/_auth.signup": typeof import("./app/routes/_auth.signup.tsx");
  "routes/_auth.login": typeof import("./app/routes/_auth.login.tsx");
  "routes/_auth.verify": typeof import("./app/routes/_auth.verify.tsx");
  "routes/_auth.onboarding": typeof import("./app/routes/_auth.onboarding.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app._index": typeof import("./app/routes/_app._index.tsx");
  "routes/_app.members": typeof import("./app/routes/_app.members.tsx");
  "routes/_app.members.$id": typeof import("./app/routes/_app.members.$id.tsx");
  "routes/_app.staff": typeof import("./app/routes/_app.staff.tsx");
  "routes/_app.plans": typeof import("./app/routes/_app.plans.tsx");
  "routes/_app.payments": typeof import("./app/routes/_app.payments.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};