// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/members": {
    params: {};
  };
  "/members/:id": {
    params: {
      "id": string;
    };
  };
  "/staff": {
    params: {};
  };
  "/staff/:id": {
    params: {
      "id": string;
    };
  };
  "/plans": {
    params: {};
  };
  "/payments": {
    params: {};
  };
  "/attendance": {
    params: {};
  };
  "/zombies": {
    params: {};
  };
  "/feedback": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/join/:qrToken": {
    params: {
      "qrToken": string;
    };
  };
  "/staff-apply/:qrToken": {
    params: {
      "qrToken": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/logout" | "/signup" | "/login" | "/verify" | "/onboarding" | "/forgot-password" | "/reset-password" | "/members" | "/members/:id" | "/staff" | "/staff/:id" | "/plans" | "/payments" | "/attendance" | "/zombies" | "/feedback" | "/gallery" | "/join/:qrToken" | "/staff-apply/:qrToken" | "/*";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/signup" | "/login" | "/verify" | "/onboarding" | "/forgot-password" | "/reset-password";
  };
  "routes/_auth.signup.tsx": {
    id: "routes/_auth.signup";
    page: "/signup";
  };
  "routes/_auth.login.tsx": {
    id: "routes/_auth.login";
    page: "/login";
  };
  "routes/_auth.verify.tsx": {
    id: "routes/_auth.verify";
    page: "/verify";
  };
  "routes/_auth.onboarding.tsx": {
    id: "routes/_auth.onboarding";
    page: "/onboarding";
  };
  "routes/_auth.forgot-password.tsx": {
    id: "routes/_auth.forgot-password";
    page: "/forgot-password";
  };
  "routes/_auth.reset-password.tsx": {
    id: "routes/_auth.reset-password";
    page: "/reset-password";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/members" | "/members/:id" | "/staff" | "/staff/:id" | "/plans" | "/payments" | "/attendance" | "/zombies" | "/feedback" | "/gallery";
  };
  "routes/_app._index.tsx": {
    id: "routes/_app._index";
    page: "/";
  };
  "routes/_app.members.tsx": {
    id: "routes/_app.members";
    page: "/members";
  };
  "routes/_app.members.$id.tsx": {
    id: "routes/_app.members.$id";
    page: "/members/:id";
  };
  "routes/_app.staff.tsx": {
    id: "routes/_app.staff";
    page: "/staff";
  };
  "routes/_app.staff.$id.tsx": {
    id: "routes/_app.staff.$id";
    page: "/staff/:id";
  };
  "routes/_app.plans.tsx": {
    id: "routes/_app.plans";
    page: "/plans";
  };
  "routes/_app.payments.tsx": {
    id: "routes/_app.payments";
    page: "/payments";
  };
  "routes/_app.attendance.tsx": {
    id: "routes/_app.attendance";
    page: "/attendance";
  };
  "routes/_app.zombies.tsx": {
    id: "routes/_app.zombies";
    page: "/zombies";
  };
  "routes/_app.feedback.tsx": {
    id: "routes/_app.feedback";
    page: "/feedback";
  };
  "routes/_app.gallery.tsx": {
    id: "routes/_app.gallery";
    page: "/gallery";
  };
  "routes/join.$qrToken.tsx": {
    id: "routes/join.$qrToken";
    page: "/join/:qrToken";
  };
  "routes/staff-apply.$qrToken.tsx": {
    id: "routes/staff-apply.$qrToken";
    page: "/staff-apply/:qrToken";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/_auth.signup": typeof import("./app/routes/_auth.signup.tsx");
  "routes/_auth.login": typeof import("./app/routes/_auth.login.tsx");
  "routes/_auth.verify": typeof import("./app/routes/_auth.verify.tsx");
  "routes/_auth.onboarding": typeof import("./app/routes/_auth.onboarding.tsx");
  "routes/_auth.forgot-password": typeof import("./app/routes/_auth.forgot-password.tsx");
  "routes/_auth.reset-password": typeof import("./app/routes/_auth.reset-password.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/_app._index": typeof import("./app/routes/_app._index.tsx");
  "routes/_app.members": typeof import("./app/routes/_app.members.tsx");
  "routes/_app.members.$id": typeof import("./app/routes/_app.members.$id.tsx");
  "routes/_app.staff": typeof import("./app/routes/_app.staff.tsx");
  "routes/_app.staff.$id": typeof import("./app/routes/_app.staff.$id.tsx");
  "routes/_app.plans": typeof import("./app/routes/_app.plans.tsx");
  "routes/_app.payments": typeof import("./app/routes/_app.payments.tsx");
  "routes/_app.attendance": typeof import("./app/routes/_app.attendance.tsx");
  "routes/_app.zombies": typeof import("./app/routes/_app.zombies.tsx");
  "routes/_app.feedback": typeof import("./app/routes/_app.feedback.tsx");
  "routes/_app.gallery": typeof import("./app/routes/_app.gallery.tsx");
  "routes/join.$qrToken": typeof import("./app/routes/join.$qrToken.tsx");
  "routes/staff-apply.$qrToken": typeof import("./app/routes/staff-apply.$qrToken.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};